[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.dependencies]
anyhow = "1.0.78"
grass = "0.13.1"
indexmap = "2.1.0"
indoc = "2.0.4"
pulldown-cmark = "0.9.3"
razorbill = { path = "crates/razorbill" }
regex = "1.10.2"
serde = "1.0.194"
thiserror = "1.0.56"
toml = "0.8.8"
