[package]
name = "blog"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
razorbill.workspace = true
tokio = { workspace = true, features = ["full"] }
