[package]
name = "razorbill"
version = "0.1.0"
edition = "2021"

[dependencies]
grass.workspace = true
indexmap.workspace = true
pulldown-cmark.workspace = true

[dev-dependencies]
indoc.workspace = true
