[package]
name = "razorbill"
version = "0.1.0"
edition = "2021"

[dependencies]
grass.workspace = true
indexmap.workspace = true
pulldown-cmark.workspace = true
regex.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
toml.workspace = true
url.workspace = true
walkdir.workspace = true

[dev-dependencies]
indoc.workspace = true
